#!/bin/bash
#
# Poky Automated Build Server Release Generation Script. This script
# takes output generated during an autobuidler build set and copies it
# into the sepcified deployment base directory.
#
# Copyright (C) 2011 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

RELEASE_TYPE=$1
DEPLOY_DIR=$2
LINKNAME=$3

function usage() {
	echo "Usage: $0 [nightly|weekly|milestone] <deploy-base-directory> <linkname>"
}

if [ $# != 3 ]; then
	usage
	exit 1
fi

if [[ "x$RELEASE_TYPE" != "xnightly" && "x$RELEASE_TYPE" != "xweekly" && "x$RELEASE_TYPE" != "xmilestone" ]]; then
	echo "Error: Unknown release type '$RELEASE_TYPE'"
	usage
	exit 1
fi

if [ ! -d $DEPLOY_DIR/$RELEASE_TYPE ]; then
    echo "Error: Release directory '$DEPLOY_DIR/$RELEASE_TYPE' does not exist"
    exit 1
fi

if [ ! -e deploy-dir ]; then
	echo "Error: there is no timestamp file"
	exit 1
fi

BUILDSTAMP=`cat deploy-dir`
# Remove the old symlink and the relink to the directory holding nightly 
rm $DEPLOY_DIR/$RELEASE_TYPE/CURRENT
ln -s $DEPLOY_DIR/$RELEASE_TYPE/$BUILDSTAMP $DEPLOY_DIR/$RELEASE_TYPE/CURRENT
exit 0

echo "Done"
