#!/bin/bash
#
# Copy the Eclipse tools needed for building Eclipse plugins. These are
# expected to be stored in a cache directory TOOLCACHE
#
# Copyright (C) 2011 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

TOOLCACHE="$HOME/eclipse-buildtools"

usage() {
	echo "Usage: $0 [standalone|combo]"
	echo "'standalone' mode is for building within another Poky build"
	exit 1
}

if [ $# -ne 1 ]; then
	usage
fi

MODE=$1
CURRDIR=`pwd`
CURRDIR=`readlink -f $CURRDIR`

cd $CURRDIR
echo "Changed to $CURRDIR"

if [ "$MODE" = "standalone" ]; then
	echo "Copying eclipse buildtools to $CURRDIR/"
	cp -a $TOOLCACHE/* .
elif [ "$MODE" = "combo" ]; then
	echo "Copying eclipse buildtools to $CURRDIR/eclipse-plugin/"
	cp -a $TOOLCACHE/* eclipse-plugin/
else
	echo "Error: unknown option '$MODE'"
	usage
fi
