#!/bin/bash
#
# Yocto Automated Build Server Sanity Test Script
#
# Copyright (C) 2011 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

CREATE_IMAGES=$2
IMGTESTTARGET="qemuimagetest_standalone"

if [[ "$CREATE_IMAGES" == "create_images" ]]; then
	echo "Ensuring that images are built."
    IMGTESTTARGET="qemuimagetest"
fi

. $HOME/.yoctoautobuild

CURRDIR=`pwd`
CURRDIR=`readlink -f $CURRDIR`

echo "ABTARGET is $ABTARGET"
echo "Commands are $@"

cd $CURRDIR

echo "Changed to $CURRDIR"

BDIR="build"
. ./oe-init-build-env

CONFFILE="./conf/auto.conf"

# This script is to only be run *after* an image has been fully
echo 'IMAGETEST = "qemu"' >> "$CONFFILE"

# Little-known bash trick to test whether a port is in use:
(echo > /dev/tcp/localhost/5901) 2> /dev/null
if [ $? -ne 0 ]; then
	echo "Starting a VNC server on :1"
	vncserver :1
else
	echo "Will use a VNC server already running on :1"
fi

DISPLAY=localhost:1 bitbake $@ -c $IMGTESTTARGET

retval=$?

rm -f "$CONFFILE"

exit $retval
