#!/bin/bash
#
# Simply mirror the DL_DIR from a poky world build to an arbitrary
# destination dir (usually a web-accessible directory). Prune out
# checksum files.
#
# Copyright (C) 2011 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


function usage() {
	echo "Usage: $0 DL_DIR DEST_DIR"
	echo "Where DL_DIR is the $DL_DIR from a yocto world build,"
	echo "and DEST_DIR is where you want the mirror created."
}

if [ $# != 2 ]; then
	usage
	exit 1
fi

DL_DIR=$1
DEST_DIR=$2

if [[ ! -d "$DL_DIR" || ! -d "$DEST_DIR" ]]; then
	echo "Error: source or destination directory do not exist"
	usage
	exit 1
fi

# Append a / to both dirs if they were not included (rsync needs this)
if [[ ! "$DL_DIR" =~ /$ ]]; then
	DL_DIR=`echo "$DL_DIR" | sed 's/$/\//'`
fi
if [[ ! "$DEST_DIR" =~ /$ ]]; then
	DEST_DIR=`echo "$DEST_DIR" | sed 's/$/\//'`
fi

rsync -av --exclude "*.md5" "$DL_DIR" "$DEST_DIR"
# Clean up permissions, as the default autobuilder sources are 777 by default
chmod -R og-w $DEST_DIR
