#!/usr/bin/env python

import os, sys

def ver_compare(x, y):
    try:
        a = x.split("-")
        b = y.split("-")
        a1 = int(a[0])
        a2 = int(a[1])
        b1 = int(b[0])
        b2 = int(b[1])
        if a1 == b1:
            if a2 < b2:
                return 1
            if a2 == b2:
                return 0
            return -1
        if a1 < b1:
            return 1
        return -1
    except:
        return 1

a = os.listdir(sys.argv[1])
a.sort(ver_compare)
for i in a:
    print i

