#!/bin/bash
#
# Yocto Autobuilder script to maintain a shared state prebuilds area
# for public consumption. We don't use rsync because we only sync
# files based on their filenames, not their checksums or timestamps.
#
# Copyright (C) 2011 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

WEBDIR=$SSTATE_PUBLISH_DIR
SSTATE_DIR=$SOURCE_SSTATE_DIR
CURRDIR=`pwd`
CURRDIR=`readlink -f $CURRDIR`

cd $CURRDIR
echo "Changed to $CURRDIR"

if [ ! -d "$WEBDIR" ]; then
	echo "Error: $WEBDIR does not exist"
	exit 1
fi
echo "Shared prebuilds target directory is $WEBDIR"

if [ ! -d $SSTATE_DIR ]; then
	echo "Error: I do not see a sstate-cache directory"
	exit 1
fi

cd $SSTATE_DIR

# Copy prebuilds which do not exist in the target directory
for file in *; do
	#echo "I see $file"
	if [ ! -f "$WEBDIR/$file" ]; then
		echo "Copying $file to shared prebuilds area"
		cp "$file" "$WEBDIR/"
	fi
done

cd "$WEBDIR"

# Clean up obsolete prebuilds by deleting files which don't exist
# in the source directory
for file in *; do
	#echo "I see $file"
	if [ ! -f "$SSTATE_DIR/$file" ]; then
		echo "Deleting obsoleted prebuild $file"
		rm -f "$file"
	fi
done

exit 0
