#!/bin/sh
#
# Copyright (C) 2011 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

. $HOME/.profile
. $HOME/.yoctoautobuild

cd $CONTROLPATH
git pull origin master:master --quiet 1> /dev/null
cmp -s $CONTROLPATH/config/yoctoABConfig.py $BMASTER/yoctoABConfig.py
if [ $? != "0" ]; then
    cp $CONTROLPATH/config/yoctoABConfig.py $BMASTER/yoctoABConfig.py
    kill -HUP `cat $BMASTER/twistd.pid`
fi

