#!/bin/bash
#
# This script is used to generate a compressed tarball of the Poky
# metadata.
#
# Copyright (C) 2011 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

usage() {
	echo "Usage: $0 <release-name> <version> <branch>"
	echo "Where a release name of 'datestamp' will generate a datestamp"
	exit 1
}

RELEASE=$1
VERSION=$2
BRANCH=$3

if [[ -z "$RELEASE" || -z "$VERSION" ]]; then
	echo "$0: missing argument"
	usage
fi

if [[ -z "$BRANCH" ]]; then
	$BRANCH = "master"
fi

BASEDIR=yocto-tarball

mkdir -p $BASEDIR/yocto
# Need to do a git clone of the yocto repo here!
git archive $BRANCH | tar -x -C ./$BASEDIR/yocto
if [ ! -e "$BASEDIR/yocto/LICENSE" ]; then
	echo "Error: I do not see a Poky source tree under $BASEDIR/yocto/"
	exit 1
fi
cd $BASEDIR && rm yocto/.gitignore

# Rename the yocto directory to use a datestamp or release name
if [ "$RELEASE" = "datestamp" ]; then
	DATESTAMP=`date +%Y%m%d`
	mv yocto yocto-$DATESTAMP-$VERSION
	echo "Generating yocto-$DATESTAMP-$VERSION.tar.bz2:"
	tar cvjf yocto-$DATESTAMP-$VERSION.tar.bz2 yocto-$DATESTAMP-$VERSION
	if [ $? -ne 0 ]; then
		echo "Error generating 'yocto-$DATESTAMP-$VERSION.tar.bz2'"
		exit 1
	fi	
else
	mv yocto yocto-$RELEASE-$VERSION
	echo "Generating yocto-$RELEASE-$VERSION.tar.bz2:"
	tar cvjf yocto-$RELEASE-$VERSION.tar.bz2 yocto-$RELEASE-$VERSION
	if [ $? -ne 0 ]; then
		echo "Error generating 'yocto-$RELEASE-$VERSION.tar.bz2'"
		exit 1
	fi	
fi
