#!/bin/bash
#
# Run the command given as arguments only if the build does not have
# a 'BuildFailure' file in its build directory.

if [ -e "BuildFailure" ]; then
	echo "Build failure detected in this build set - NOT running '$@'"
	exit 0
fi

$@
