#!/bin/bash
#
# Move the tmp dir and shared state cache dir into a safe area so the
# Buildbot SCM system can blow away the build directory during updates.

CMD=$1

if [ "x$CMD" = "xbackup" ]; then
	if [ ! -d ./build/conf ]; then
		echo "No build/conf directory found; assuming this is a build from scratch"
		# Create empty directores so that restore will work unmodified
		mkdir ../tmp.protected
		mkdir ../sstate-cache.protected
		exit 0
	fi

	if [ ! -d "./build/tmp" ]; then
		PWD=`pwd`
		echo "Error: There is no build/tmp directory under $PWD"
		exit 1
	fi

	mv build/tmp ../tmp.protected
	if [ ! -d ../tmp.protected ]; then
		echo "Error moving build/tmp to a protected area"
		exit 1
	fi

	mv build/sstate-cache ../sstate-cache.protected
	if [ ! -d ../sstate-cache.protected ]; then
		echo "Error moving build/sstate-cache to a protected area"
		exit 1
	fi

elif [ "x$CMD" == "xrestore" ]; then
	if [ ! -d ../tmp.protected ]; then
		PWD=`pwd`
		echo "Error: There is no ../tmp.protected directory to restore under $PWD"
		exit 1
	fi

	mkdir build
	mv ../tmp.protected build/tmp
	if [ ! -d build/tmp ]; then
		echo "Error moving tmp.protected dir back into build/tmp"
		exit 1
	fi

	mv ../sstate-cache.protected build/sstate-cache
	if [ ! -d build/sstate-cache ]; then
		echo "Error moving sstate-cache.protected dir back into build/sstate-cache"
		exit 1
	fi
else
	echo "Unknown command '$CMD'"
	echo "Commands are 'backup' or 'restore'"
	exit 1
fi

exit 0
